[tool.poetry]
name = "nsdu"
version = "0.2.1"
description = "A tool to format and update NationStates dispatches."
authors = ["watarinishin <watarichanno@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
nationstates = "~3.0.2"
toml = "~0.10.2"
bbcode = "~1.1.0"
Jinja2 = "~2.11.3"
appdirs = "~1.4.4"
pluggy = "~0.13.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
coverage = "^5.5"
pytest-cov = "^2.11.1"
pylint = "^2.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nsdu = "nsdu.__main__:main"
